{% set name = "litecli" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee9e2a93d193a555c0e661ed083943a6f932a9c8e8c267b689b469f9ac7a3e0c

build:
  number: 0
  entry_points:
    - litecli = litecli.main:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=4.1
    - pygments >=1.6
    - prompt_toolkit >=3.0.3,<4.0.0
    - sqlparse
    - configobj >=5.0.5
    - cli_helpers >=2.2.1
    - python >=3.7

test:
  imports:
    - litecli
    - litecli.packages
    - litecli.packages.special
  commands:
    - litecli --version

about:
  home: https://litecli.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLI for SQLite Databases with auto-completion and syntax highlighting.
  doc_url: https://litecli.com/features/
  dev_url: https://github.com/dbcli/litecli/

extra:
  recipe-maintainers:
    - cofinoa
