{% set name = "litecli" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdef4f02a9b18f3bafcae080fcddff8031eabd7d0c0cefa0ac157adbc384e220

build:
  number: 1
  entry_points:
    - litecli = litecli.main:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cli_helpers >=2.2.1
    - click >=4.1
    - configobj >=5.0.5
    - prompt_toolkit >=3.0.3,<4.0.0
    - pygments >=1.6
    - sqlparse >=0.4.4
    - llm >=0.25.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - litecli
    - litecli.packages
    - litecli.packages.special
  commands:
    - litecli --version

about:
  home: https://litecli.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLI for SQLite Databases with auto-completion and syntax highlighting.
  doc_url: https://litecli.com/features/
  dev_url: https://github.com/dbcli/litecli/

extra:
  recipe-maintainers:
    - cofinoa
