{% set name = "litecli" %}
{% set version = "1.14.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abdfcd75f6c5fb42aa9e6e0c409ae84090998b105cf875ae0b157a1f1ba5653b

build:
  number: 1
  entry_points:
    - litecli = litecli.main:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=4.1
    - pygments >=1.6
    - prompt_toolkit >=3.0.3,<4.0.0
    - sqlparse
    - configobj >=5.0.5
    - cli_helpers >=2.2.1
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - litecli
    - litecli.packages
    - litecli.packages.special
  commands:
    - litecli --version

about:
  home: https://litecli.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLI for SQLite Databases with auto-completion and syntax highlighting.
  doc_url: https://litecli.com/features/
  dev_url: https://github.com/dbcli/litecli/

extra:
  recipe-maintainers:
    - cofinoa
